# Generated by Django 4.1.2 on 2022-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('second_name', models.CharField(max_length=240, null=True)),
                ('date_of_graduation', models.DateTimeField()),
                ('date_of_employment', models.DateTimeField()),
                ('position', models.CharField(max_length=20, null=True)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
