# Generated by Django 4.1.2 on 2022-10-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='positio',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary')], max_length=1, null=True),
        ),
    ]
