# Generated by Django 4.1.2 on 2022-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_positio_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisors',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('H', 'Human Resource'), ('C', 'Chief executive officer'), ('M', 'Manager'), ('P', 'President'), ('P', 'Product Manager'), ('F', 'Finance Manager'), ('A', 'Accountant'), ('O', 'Others')], max_length=30, null=True),
        ),
    ]
