# Generated by Django 4.1.2 on 2022-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
